import LinkedListClass

x = LinkedListClass.LinkedList()

x.insert_at_start(1)
print("lll    ", x.length)
x.insert_at_start(2)
print("lll    ", x.length)
x.insert_at_start(3)
print("lll    ", x.length)
x.insert_at_start(4)
print("lll    ", x.length)
print(x.pop_last())
print("lll    ", x.length)
print(x.pop_last())
print("lll    ", x.length)
print(x.pop_last())
print("lll    ", x.length)
print(x.pop_last())
print("lll    ", x.length)
print(x.pop_last())
print("lll    ", x.length)
x.insert_at_start(5)
print("lll    ", x.length)
x.insert_at_start(6)
print("lll    ", x.length)
print(x.pop_last())
print("lll    ", x.length)
x.insert_at_start(7)
print("lll    ", x.length)


print(x)
